# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Run on all files:   pre-commit run --all-files
# - Register git hooks: pre-commit install --install-hooks
#
repos:
  # Autoformat: Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.7
    hooks:
      - id: ruff-check
        args: ["--fix", "--show-fixes", "--exit-non-zero-on-fix"]
      - id: ruff-format

  # Autoformat: markdown, yaml
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.9.6
    hooks:
      - id: prettier
        exclude: tests/.*

  # Misc...
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # v6.0.0
    # ref: https://github.com/pre-commit/pre-commit-hooks#hooks-available
    hooks:
      # Sanity checks
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-merge-conflict

      # Checks based on file type
      - id: check-toml
      - id: check-yaml

      # Detect mistakes
      - id: debug-statements
      - id: detect-private-key
      - id: forbid-submodules

      # Automatic fixes
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
        exclude: tests/.*
