# Read the Docs builds and publish our documentation
#
# Config reference: https://docs.readthedocs.io/en/stable/config-file/v2.html
#
version: 2

sphinx:
  configuration: docs/conf.py
  builder: dirhtml

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx
